services:
  laravel-franken:
    container_name: laravel-franken
    build:
      context: .
      dockerfile: worker.dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      MAX_REQUESTS: 500
    extra_hosts:
      - "host.docker.internal:host-gateway"
