version: '3'

services:
  laravel-franken:
    container_name: laravel-franken
    image: image_laravel_franken
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8001:80
    env_file:
      - .env
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - ./storage:/app/storage
