services:
  laravel-franken:
    container_name: laravel-franken
    build:
      context: .
      dockerfile: worker.dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./:/app
      - ./.env:/app/.env
      # Jangan mount ./public atau ./storage secara terpisah!
    environment:
      MAX_REQUESTS: 100
      APP_ENV: local
      APP_DEBUG: "true"
      OCTANE_SERVER_STATE_FILE: /app/storage/framework/octane-server-state.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # user: "www-data"   # <--- Hapus baris ini

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: