services:
  laravel-franken:
    container_name: laravel-franken
    image: image_laravel_franken
    build:
      dockerfile: worker.dockerfile
      context: .
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - .:/app
      - ./.env:/app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
